/**
 * The world client's own strings, English and German side by side.
 *
 * **Not** through `client/i18n/Translate.ts`. That reads its catalogue from a
 * `<lang-selector>` element, which lives in `client/_legacy/` and is
 * quarantined; without one every lookup falls back to its key, so the HUD
 * would read "world.economy.steel" on screen. Wiring the legacy component back
 * in to get four dozen strings would drag the whole quarantined component tree
 * with it.
 *
 * So: one file, both languages, and `de` typed as `Record<Key, string>` so a
 * missing German string is a compile error rather than an English word in the
 * middle of a German sentence. When the HUD grows a language picker of its
 * own, this merges into `resources/lang/` and this file becomes the loader.
 *
 * English is the source language; German is maintained in the same commit.
 */

const en = {
  "hud.watching": "Watching. Add ?nation=<n> to the URL to play one.",
  "hud.notConnected": "Not connected to the world.",
  "hud.orderAccepted": "Order accepted for tick {tick}.",
  "hud.orderRefused": "Order refused: {reason}",

  "economy.title": "Economy",
  "regent.title": "Regent",
  "regent.enabled": "Let the regent play while you are away",
  "regent.focus.economy": "Focus: economy",
  "regent.focus.military": "Focus: military",
  "regent.focus.defence": "Focus: defence",
  "regent.focus.expansion": "Focus: expansion",
  "regent.budget": "Market budget a day",
  "regent.apply": "Set the regent",
  "economy.construction": "Construction",
  "economy.industry": "Industry",
  "economy.supplyRatio": "Resources covered",
  "economy.tradeShare": "of it from trade",
  "economy.steel": "Steel",
  "economy.oil": "Oil",
  "economy.aluminium": "Aluminium",
  "economy.rubber": "Rubber",
  "economy.perDay": "{value}/day",
  "economy.stock": "{value}",

  "province.title": "Province {id}",
  "province.terrain": "Terrain",
  "province.infrastructure": "Infrastructure",
  "province.slots": "Building slots",
  "province.deposits": "Deposits",
  "province.none": "none",
  "province.owner": "Owner",
  "province.controller": "Held by",
  "province.occupied": "occupied",
  "province.unowned": "unowned",
  "province.capital": "capital",
  "province.coastal": "coastal",
  "province.attack": "Attack this province",
  "province.callOff": "Call off the attack",
  "province.invade": "Invade from the sea",
  "province.attacking": "Your front is grinding here, every tick.",
  "province.buildings": "Buildings",
  "province.build": "Build",

  "terrain.plains": "Plains",
  "terrain.highland": "Highland",
  "terrain.mountain": "Mountain",

  "queue.title": "Construction queue",
  "queue.empty": "Nothing under construction.",
  "queue.remaining": "{days} days left",
  "queue.cancel": "Cancel",

  "production.title": "Production",
  "production.factories": "Military factories",
  "production.dockyards": "Dockyards",
  "production.manpower": "Manpower",
  "production.lines": "Production lines",
  "production.noLines": "No production line yet. Nothing is being built.",
  "production.efficiency": "Efficiency",
  "production.output": "Output",
  "production.addFactory": "+ factory",
  "production.removeFactory": "\u2212 factory",
  "production.close": "Close this line",
  "production.open": "Open a line",
  "production.switchTo": "Switch \u2014 throws away {efficiency}",
  "production.stockpile": "Stockpile",
  "production.stockpileEmpty": "Nothing in store.",
  "production.divisions": "Divisions",
  "production.fronts": "Fronts",
  "air.title": "Air and sea",
  "air.zone": "Zone {zone}",
  "air.seaZone": "Sea zone {zone}",
  "air.noZones": "No zone you can see anything over.",
  "air.superiority": "{value} of the sky",
  "air.uncontested": "unopposed",
  "air.formations": "Wings",
  "air.noFormations": "No wings raised.",
  "air.onTheGround": "on the ground at province {province}",
  "air.flying": "zone {zone} \u00b7 {mission}",
  "air.bringHome": "Bring it home",
  "air.assign": "Send a wing",
  "air.send": "Send",
  "air.raise": "{what} \u2014 {cost} manpower",
  "formation.fighter_wing": "Fighter wing",
  "formation.bomber_wing": "Bomber wing",
  "formation.submarine_flotilla": "Submarine flotilla",
  "formation.escort_group": "Escort group",
  "formation.battle_fleet": "Battle fleet",
  "mission.air_superiority": "Fight for the sky",
  "mission.ground_support": "Support the ground",
  "mission.interdiction": "Cut their supply",
  "mission.strategic_bombing": "Bomb their industry",
  "mission.sea_control": "Control the sea",
  "mission.convoy_raiding": "Raid convoys",
  "mission.convoy_escort": "Escort convoys",
  "mission.invasion_support": "Support a landing",
  "production.noDivisions": "No divisions raised.",
  "production.divisionAt": "Division {id} \u00b7 province {province}",
  "production.raise": "Raise a division \u2014 {cost} manpower",
  "production.divisionState": "{strength} kit \u00b7 {supply} supply",
  "production.atSea": "Division {id} \u00b7 at sea, {ticks} ticks out",

  "building.civilian_factory": "Civilian factory",
  "building.military_factory": "Military factory",
  "building.dockyard": "Dockyard",
  "building.synthetic_oil": "Synthetic oil refinery",
  "building.synthetic_rubber": "Synthetic rubber refinery",
  "building.air_base": "Air base",
  "building.naval_base": "Naval base",
  "building.supply_hub": "Supply hub",
  "building.infrastructure": "Infrastructure level",
  "building.extraction_upgrade": "Extraction upgrade",

  "research.title": "Research",
  "research.idle": "Idle",
  "research.locked": "Locked \u2014 research a bureau to open it",
  "research.remaining": "{days} days left",
  "research.cancel": "Abandon",
  "research.start": "Research",
  "research.known": "Known",
  "research.none": "Nothing researched yet.",
  "research.needs": "needs {techs}",

  "tech.machine_tools": "Machine tools",
  "tech.precision_tooling": "Precision tooling",
  "tech.assembly_line": "Assembly line",
  "tech.excavation": "Excavation",
  "tech.deep_mining": "Deep mining",
  "tech.reinforced_concrete": "Reinforced concrete",
  "tech.research_bureau": "Research bureau",
  "tech.field_workshops": "Field workshops",
  "tech.entrenchment": "Entrenchment",

  "equipment.infantry_equipment": "Infantry equipment",
  "equipment.artillery": "Artillery",
  "equipment.armour": "Armour",
  "equipment.fighter": "Fighter",
  "equipment.bomber": "Bomber",
  "equipment.transport": "Transport",
  "equipment.convoy": "Convoy",
  "equipment.submarine": "Submarine",
  "equipment.escort": "Escort",
  "equipment.capital_ship": "Capital ship",

  "diplomacy.title": "Diplomacy",
  "diplomacy.trust": "Your trust",
  "diplomacy.trustShort": "trust {trust}",
  "diplomacy.tradeBalance": "Points in / out",
  "diplomacy.offers": "Offers to you",
  "diplomacy.noOffers": "Nobody has offered you anything.",
  "diplomacy.offered": "{type}, offered to",
  "diplomacy.accept": "Accept",
  "diplomacy.decline": "Decline",
  "diplomacy.withdraw": "Withdraw the offer",
  "diplomacy.standing": "Standing agreements",
  "diplomacy.noneStanding":
    "None. Every agreement here lasts until somebody ends it.",
  "diplomacy.terms": "{rate} {resource} for {points} construction",
  "diplomacy.youSend": "You send {terms}",
  "diplomacy.youReceive": "You receive {terms}",
  "diplomacy.cancel": "Give notice — costs {trust} trust",
  "diplomacy.noticeGiven": "You gave notice. It stops in a day.",
  "diplomacy.noticeReceived": "{nation} gave notice. It stops in a day.",
  "diplomacy.propose": "Offer an agreement",
  "diplomacy.send": "Send the offer",
  "diplomacy.market": "World market",
  "diplomacy.flows": "Standing flows",
  "diplomacy.marketRates": "buy {buy} / sell {sell}",
  "diplomacy.netFlow": "standing order: {rate}",
  "diplomacy.setOrder": "Set the standing order (per day, minus sells)",

  "agreement.non_aggression": "Non-aggression",
  "agreement.trade": "Trade",
  "agreement.alliance": "Alliance",
  "agreement.military_access": "Military access",
} as const;

export type StringKey = keyof typeof en;

const de: Record<StringKey, string> = {
  "hud.watching":
    "Nur Zuschauer. ?nation=<n> an die URL hängen, um zu spielen.",
  "hud.notConnected": "Keine Verbindung zur Welt.",
  "hud.orderAccepted": "Befehl angenommen für Tick {tick}.",
  "hud.orderRefused": "Befehl abgelehnt: {reason}",

  "economy.title": "Wirtschaft",
  "regent.title": "Regent",
  "regent.enabled": "Der Regent spielt, wenn du weg bist",
  "regent.focus.economy": "Fokus: Wirtschaft",
  "regent.focus.military": "Fokus: Militär",
  "regent.focus.defence": "Fokus: Verteidigung",
  "regent.focus.expansion": "Fokus: Expansion",
  "regent.budget": "Marktbudget pro Tag",
  "regent.apply": "Regent einstellen",
  "economy.construction": "Bau",
  "economy.industry": "Industrie",
  "economy.supplyRatio": "Rohstoffe gedeckt",
  "economy.tradeShare": "davon aus Handel",
  "economy.steel": "Stahl",
  "economy.oil": "Öl",
  "economy.aluminium": "Aluminium",
  "economy.rubber": "Gummi",
  "economy.perDay": "{value}/Tag",
  "economy.stock": "{value}",

  "province.title": "Provinz {id}",
  "province.terrain": "Gelände",
  "province.infrastructure": "Infrastruktur",
  "province.slots": "Bauplätze",
  "province.deposits": "Vorkommen",
  "province.none": "keine",
  "province.owner": "Eigentümer",
  "province.controller": "Gehalten von",
  "province.occupied": "besetzt",
  "province.unowned": "herrenlos",
  "province.capital": "Hauptstadt",
  "province.coastal": "Küste",
  "province.attack": "Diese Provinz angreifen",
  "province.callOff": "Angriff abbrechen",
  "province.invade": "Von See her anlanden",
  "province.attacking": "Hier mahlt deine Front, jeden Tick.",
  "province.buildings": "Gebäude",
  "province.build": "Bauen",

  "terrain.plains": "Ebene",
  "terrain.highland": "Hügelland",
  "terrain.mountain": "Gebirge",

  "queue.title": "Bauschlange",
  "queue.empty": "Nichts im Bau.",
  "queue.remaining": "noch {days} Tage",
  "queue.cancel": "Abbrechen",

  "production.title": "Produktion",
  "production.factories": "Militärfabriken",
  "production.dockyards": "Werften",
  "production.manpower": "Menschenreserve",
  "production.lines": "Produktionslinien",
  "production.noLines": "Noch keine Produktionslinie. Es wird nichts gebaut.",
  "production.efficiency": "Effizienz",
  "production.output": "Ausstoß",
  "production.addFactory": "+ Fabrik",
  "production.removeFactory": "\u2212 Fabrik",
  "production.close": "Linie schließen",
  "production.open": "Linie eröffnen",
  "production.switchTo": "Umstellen \u2014 wirft {efficiency} weg",
  "production.stockpile": "Lager",
  "production.stockpileEmpty": "Nichts auf Lager.",
  "production.divisions": "Divisionen",
  "production.fronts": "Fronten",
  "air.title": "Luft und See",
  "air.zone": "Zone {zone}",
  "air.seaZone": "Seezone {zone}",
  "air.noZones": "Keine Zone, über der du etwas siehst.",
  "air.superiority": "{value} des Himmels",
  "air.uncontested": "unbestritten",
  "air.formations": "Staffeln",
  "air.noFormations": "Keine Staffeln aufgestellt.",
  "air.onTheGround": "am Boden in Provinz {province}",
  "air.flying": "Zone {zone} \u00b7 {mission}",
  "air.bringHome": "Zurückholen",
  "air.assign": "Staffel entsenden",
  "air.send": "Entsenden",
  "air.raise": "{what} \u2014 {cost} Menschenreserve",
  "formation.fighter_wing": "Jagdstaffel",
  "formation.bomber_wing": "Bomberstaffel",
  "formation.submarine_flotilla": "U-Boot-Flottille",
  "formation.escort_group": "Geleitgruppe",
  "formation.battle_fleet": "Schlachtflotte",
  "mission.air_superiority": "Um den Himmel kämpfen",
  "mission.ground_support": "Den Boden unterstützen",
  "mission.interdiction": "Nachschub abschneiden",
  "mission.strategic_bombing": "Industrie bombardieren",
  "mission.sea_control": "See beherrschen",
  "mission.convoy_raiding": "Konvois jagen",
  "mission.convoy_escort": "Konvois sichern",
  "mission.invasion_support": "Landung unterstützen",
  "production.noDivisions": "Keine Divisionen aufgestellt.",
  "production.divisionAt": "Division {id} \u00b7 Provinz {province}",
  "production.raise": "Division aufstellen \u2014 {cost} Menschenreserve",
  "production.divisionState": "{strength} Ausrüstung \u00b7 {supply} Nachschub",
  "production.atSea": "Division {id} \u00b7 auf See, noch {ticks} Ticks",

  "building.civilian_factory": "Zivile Fabrik",
  "building.military_factory": "Militärfabrik",
  "building.dockyard": "Werft",
  "building.synthetic_oil": "Synthetische Ölraffinerie",
  "building.synthetic_rubber": "Synthetische Gummiraffinerie",
  "building.air_base": "Luftwaffenbasis",
  "building.naval_base": "Marinebasis",
  "building.supply_hub": "Nachschubdepot",
  "building.infrastructure": "Infrastrukturstufe",
  "building.extraction_upgrade": "Förderausbau",

  "research.title": "Forschung",
  "research.idle": "Untätig",
  "research.locked": "Gesperrt \u2014 ein Forschungsamt öffnet ihn",
  "research.remaining": "noch {days} Tage",
  "research.cancel": "Abbrechen",
  "research.start": "Erforschen",
  "research.known": "Bekannt",
  "research.none": "Noch nichts erforscht.",
  "research.needs": "braucht {techs}",

  "tech.machine_tools": "Werkzeugmaschinen",
  "tech.precision_tooling": "Präzisionswerkzeuge",
  "tech.assembly_line": "Fließband",
  "tech.excavation": "Abbautechnik",
  "tech.deep_mining": "Tiefbau",
  "tech.reinforced_concrete": "Stahlbeton",
  "tech.research_bureau": "Forschungsamt",
  "tech.field_workshops": "Feldwerkstätten",
  "tech.entrenchment": "Feldbefestigung",

  "equipment.infantry_equipment": "Infanterieausrüstung",
  "equipment.artillery": "Artillerie",
  "equipment.armour": "Panzer",
  "equipment.fighter": "Jäger",
  "equipment.bomber": "Bomber",
  "equipment.transport": "Transportflugzeug",
  "equipment.convoy": "Geleitzug",
  "equipment.submarine": "U-Boot",
  "equipment.escort": "Geleitschiff",
  "equipment.capital_ship": "Großkampfschiff",

  "diplomacy.title": "Diplomatie",
  "diplomacy.trust": "Dein Vertrauen",
  "diplomacy.trustShort": "Vertrauen {trust}",
  "diplomacy.tradeBalance": "Punkte ein / aus",
  "diplomacy.offers": "Angebote an dich",
  "diplomacy.noOffers": "Dir hat niemand etwas angeboten.",
  "diplomacy.offered": "{type}, angeboten an",
  "diplomacy.accept": "Annehmen",
  "diplomacy.decline": "Ablehnen",
  "diplomacy.withdraw": "Angebot zurückziehen",
  "diplomacy.standing": "Laufende Abkommen",
  "diplomacy.noneStanding":
    "Keine. Jedes Abkommen hier läuft, bis es jemand beendet.",
  "diplomacy.terms": "{rate} {resource} für {points} Bau",
  "diplomacy.youSend": "Du lieferst {terms}",
  "diplomacy.youReceive": "Du erhältst {terms}",
  "diplomacy.cancel": "Kündigen — kostet {trust} Vertrauen",
  "diplomacy.noticeGiven": "Du hast gekündigt. In einem Tag endet es.",
  "diplomacy.noticeReceived": "{nation} hat gekündigt. In einem Tag endet es.",
  "diplomacy.propose": "Abkommen anbieten",
  "diplomacy.send": "Angebot senden",
  "diplomacy.market": "Weltmarkt",
  "diplomacy.flows": "Laufende Flüsse",
  "diplomacy.marketRates": "Kauf {buy} / Verkauf {sell}",
  "diplomacy.netFlow": "Dauerauftrag: {rate}",
  "diplomacy.setOrder": "Dauerauftrag setzen (pro Tag, negativ verkauft)",

  "agreement.non_aggression": "Nichtangriff",
  "agreement.trade": "Handel",
  "agreement.alliance": "Bündnis",
  "agreement.military_access": "Durchmarschrecht",
};

const CATALOGUES: Record<string, Record<StringKey, string>> = { en, de };

/**
 * The language, from the browser, once.
 *
 * No picker yet — one belongs with the account screens rather than ahead of
 * them. Anything that is not German gets English.
 */
function language(): string {
  const preferred =
    typeof navigator === "undefined" ? "en" : (navigator.language ?? "en");
  return preferred.toLowerCase().startsWith("de") ? "de" : "en";
}

const catalogue = CATALOGUES[language()];

/** `{name}` placeholders, substituted positionally by name. */
export function t(
  key: StringKey,
  params: Record<string, string | number> = {},
): string {
  const template = catalogue[key];
  return template.replace(/\{(\w+)\}/g, (whole, name: string) =>
    name in params ? String(params[name]) : whole,
  );
}
